name: Run PPG Python Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" :

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show files in repo
        run: |
          ls -R

      - name: Run handling null values script
        run: |
          python "handling null values.py"

      - name: Run series plot script
        run: |
          python "series plot.py"

      - name: Run decomposition script
        run: |
          python "decomposition.py"

      - name: Run feature engineering script
        run: |
          python "feature engineering.py"

      - name: Run bonus task script
        run: |
          python "bonus task.py"

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ppg-output-files
          path: |
            *.png
            *.csv
            *.jpg
            *.jpeg
            *.txt
